---
- name: configure local
  hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
#    - name: brew-update
#      community.general.homebrew:
#        update_homebrew: yes
#    - name: brew-packages
#      community.general.homebrew:
#        name: "{{ item }}"
#        state: latest
#        update_homebrew: no
#      with_items: "{{ brew_packages }}"
## TODO homebrew install/reinstall mactex cask
## TODO install hex `mix local.hex`
## TODO link java sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
    - name: configure-vim-directories
      ansible.builtin.file:
        path: "{{ item.dir }}"
        state: directory
      with_items: "{{ vim.config_dirs }}"
    - name: git-vim-opt-plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ vim.plugins.directory }}/opt/{{ item | regex_replace('[a-z-]+/([a-z-]+)', '\\1') }}"
      with_items: "{{ vim.plugins.opt }}"
    - name: git-vim-start-plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ vim.plugins.directory }}/start/{{ item | regex_replace('[a-z-]+/([a-z-]+)', '\\1') }}"
      with_items: "{{ vim.plugins.start }}"
    - name: copy-vim-dotfiles
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items: "{{ vim.dotfiles }}"

    - name: configure-bash-directories
      ansible.builtin.file:
        path: "{{ item.dir }}"
        state: directory
      with_items: "{{ bash.config_dirs }}"
    - name: copy-bash-dotfiles
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items: "{{ bash.dotfiles }}"
    - name: copy-bash-scripts
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: u+rwx
      with_items: "{{ bash.scripts }}"

    - name: configure-mvn-directories
      ansible.builtin.file:
        path: "{{ item.dir }}"
        state: directory
      with_items: "{{ maven.config_dirs }}"
    - name: copy-mvn-config
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items: "{{ maven.dotfiles }}"
## TODO change default shell
