---
- name: configure local
  hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: brew-update
      community.general.homebrew:
        update_homebrew: yes
    - name: brew-packages
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        update_homebrew: no
      with_items: "{{ brew_packages }}"
# TODO homebrew install/reinstall mactex cask
# TODO install hex `mix local.hex`
# TODO link java sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
    - name: git-vim-opt-plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ vim_plugins_directory }}/opt/{{ item | regex_replace('[a-z-]+/([a-z-]+)', '\\1') }}"
      with_items: "{{ vim_plugins.opt }}"
    - name: git-vim-start-plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ vim_plugins_directory }}/start/{{ item | regex_replace('[a-z-]+/([a-z-]+)', '\\1') }}"
      with_items: "{{ vim_plugins.start }}"
    - name: configure-directories
      ansible.builtin.file:
        path: "{{ item.dir }}"
        state: directory
      with_items: "{{ config_dirs }}"
    - name: link-dotfiles
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items: "{{ dotfiles }}"
# TODO change default shell
