---
- name: configure local
  hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: brew-update
      community.general.homebrew:
        update_homebrew: yes
    - name: brew-packages
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        update_homebrew: no
      with_items: "{{ brew_packages }}"
    - name: git-vim-opt-plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ vim_plugins.directory }}/opt/{{ item | regex_replace('[a-z-]+/([a-z-]+)', '\\1') }}"
      with_items: "{{ vim_plugins.opt }}"
    - name: git-vim-start-plugins
      ansible.builtin.git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ vim_plugins.directory }}/start/{{ item | regex_replace('[a-z-]+/([a-z-]+)', '\\1') }}"
      with_items: "{{ vim_plugins.start }}"
#    - name: link-vimrc
#      ansible.builtin.file:
#        src: /Users/srang/code/opensource/srang/dotfiles/.vimrc
#        dest: /Users/srang/.vimrc
#        state: link
#    - name: link-global-git-ignore
#      ansible.builtin.file:
#        src: /Users/srang/code/opensource/srang/dotfiles/.global_ignore
#        dest: /Users/srang/.global_ignore
#        state: link
#    - name: link-local-bin
#      ansible.builtin.file:
#        src: /Users/srang/code/opensource/srang/dotfiles/bin
#        dest: /Users/srang/.bin
#        state: link
#    - name: link-bashrc
#      ansible.builtin.file:
#        src: /Users/srang/code/opensource/srang/dotfiles/.bashrc
#        dest: /Users/srang/.bashrc
#        state: link
#    - name: link-essential-vimrc
#      ansible.builtin.file:
#        src: /Users/srang/code/opensource/srang/dotfiles/.essential_vimrc
#        dest: /Users/srang/.essential_vimrc
#        state: link
#    - name: link-vimrc
#      ansible.builtin.file:
#        src: /Users/srang/code/opensource/srang/dotfiles/.vimrc
#        dest: /Users/srang/.vimrc
#        state: link
