---
- name: configure local
  hosts: localhost
  tasks:
    - name: brew-git
      community.general.homebrew: 
        name: git
        state: latest
        update_homebrew: yes
    - name: brew-vim
      community.general.homebrew: 
        name: vim
        state: latest
        update_homebrew: no
    - name: brew-ansible
      community.general.homebrew: 
        name: ansible
        state: latest
        update_homebrew: no
    - name: brew-cowsay
      community.general.homebrew: 
        name: cowsay
        state: latest
        update_homebrew: no
    - name: git-vim-plug-emmet
      ansible.builtin.git:
        repo: 'https://github.com/mattn/emmet-vim.git'
        dest: /Users/srang/.vim/pack/vendor/opt/emmet
    - name: git-vim-plug-vimtex
      ansible.builtin.git:
        repo: 'https://github.com/lervag/vimtex.git'
        dest: /Users/srang/.vim/pack/vendor/opt/vimtex
    - name: git-vim-plug-airline
      ansible.builtin.git:
        repo: 'https://github.com/vim-airline/vim-airline.git'
        dest: /Users/srang/.vim/pack/vendor/start/airline
    - name: git-vim-plug-css
      ansible.builtin.git:
        repo: 'https://github.com/ap/vim-css-color.git'
        dest: /Users/srang/.vim/pack/vendor/start/css-color
    - name: git-vim-plug-lexical
      ansible.builtin.git:
        repo: 'https://github.com/reedes/vim-lexical.git'
        dest: /Users/srang/.vim/pack/vendor/start/lexical
    - name: git-vim-plug-nerdcommenter
      ansible.builtin.git:
        repo: 'https://github.com/preservim/nerdcommenter.git'
        dest: /Users/srang/.vim/pack/vendor/start/nerdcommenter
    - name: git-vim-plug-nerdtree
      ansible.builtin.git:
        repo: 'https://github.com/preservim/nerdtree.git'
        dest: /Users/srang/.vim/pack/vendor/start/nerdtree
    - name: git-vim-plug-surround
      ansible.builtin.git:
        repo: 'https://github.com/tpope/vim-surround.git'
        dest: /Users/srang/.vim/pack/vendor/start/surround
    - name: git-vim-plug-syntastic
      ansible.builtin.git:
        repo: 'https://github.com/scrooloose/syntastic.git'
        dest: /Users/srang/.vim/pack/vendor/start/syntastic
    - name: git-vim-plug-elixir
      ansible.builtin.git:
        repo: 'https://github.com/elixir-editors/vim-elixir.git'
        dest: /Users/srang/.vim/pack/vendor/start/vim-elixir
    - name: git-vim-plug-liquid
      ansible.builtin.git:
        repo: 'https://github.com/tpope/vim-liquid.git'
        dest: /Users/srang/.vim/pack/vendor/start/vim-liquid
    - name: link-vimrc
      ansible.builtin.file:
        src: /Users/srang/code/opensource/srang/dotfiles/.vimrc
        dest: /Users/srang/.vimrc
        state: link
    - name: link-global-git-ignore
      ansible.builtin.file:
        src: /Users/srang/code/opensource/srang/dotfiles/.global_ignore
        dest: /Users/srang/.global_ignore
        state: link
